---
  - name: Add Bitnami Helm repo
    command: helm repo add bitnami https://charts.bitnami.com/bitnami
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"

  - name: Check if kubeapps is installed
    command: helm status kubeapps -n kubeapps
    register: helm_status
    ignore_errors: yes
    changed_when: false

  - name: Install kubeapps {{kube_kubeapps_chart_version}}
    command: helm install kubeapps --namespace kubeapps --create-namespace bitnami/kubeapps
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"
    when: helm_status.rc != 0

  - template: src=kubeapps-ingress.j2 dest=/tmp/kubeapps-ingress.yaml
  - command: kubectl apply -f /tmp/kubeapps-ingress.yaml
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"